### ISSUE TITLE
Set up bounties for contributors to hunt.

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre#108]
We have a lot of things we would like, i.e., https://roadmap.maplibre.org/tabs/16-overview and many more.

Currently, no resources are allocated for anything to drive development.

With ESRI's recent adoption of MapLibre, it would arguably make a lot of sense to collaborate with that deep expertise on the compatibility with the ArcGIS stack (on our roadmap)

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre/wiki/Bounty-System

**Comment by wipfli** [comment]
https://twitter.com/rust_foundation/status/1579889452977369089?t=7oeAH4eqc0S3eToN9vvy3g&s=19

**Comment by wipfli** [comment]
Let's track the progress on the bounty system in #125 only.
