### ISSUE TITLE
Video conference system

### ISSUE THREAD

**Issue by klokan** [maplibre/maplibre#111]
Switch to organizational controlled system.

Additional benefits wanted:
- Note taking (transcriptions?)

Zoom or Google Meet ?

**Comment by wipfli** [comment]
We also may want to have our own google drive for collaboration. We might get it for free here: https://docs.opencollective.foundation/what-we-offer/emails

**Comment by wipfli** [comment]
We can move to the opencollective gmail with this form: https://docs.google.com/forms/d/e/1FAIpQLSfV49KOo9xUAollJU94T52nkTUdoJ1JnFD7Di_zmUolTBn06Q/viewform

**Comment by wipfli** [comment]
If maplibre.org is already associated with a gmail account, which I think it is, we will have to dissociate it before we can apply to the form. This will lead to some interruption of the service.

**Comment by wipfli** [comment]
I suggest to do this work on Monday, Oct 3rd, 2022 such that we have some time before the next Technical Steering Committee meeting where we will want to use our current google account for meet and notes taking in Google Docs.

**Comment by wipfli** [comment]
The other option is to use the starter plan for USD 6 per month from google workspace. It has all we need I think and we have full control. https://workspace.google.com/pricing.html

**Comment by HarelM** [comment]
I still think zoom is a lot better, don't know about pricing though...

**Comment by wipfli** [comment]
I also like zoom a lot. It is USD 140 per year. Should I get it?

**Comment by wipfli** [comment]
We can also keep the google drive as is for now, if @klokan agrees. I think no change in google drive and a zoom subscription would overall be the easiest and cheapest solution at the moment.

**Comment by klokan** [comment]
No problem on my side. Zero extra costs, zero work.

**Comment by HarelM** [comment]
140 USD a year seems like a good investment from my point of view.

**Comment by wipfli** [comment]
OK. I created a zoom account for us. At the moment, zoom's payment system has technical problems and I could not buy a subscription. But we have an account now and it is stored in the bitwarden key manager.

**Comment by wipfli** [comment]
We have a subscription now. Was USD 150 for one year.
