### ISSUE TITLE
Streamline notes taking and publishing process

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#119]
At the moment, we take the notes of meetings together in a google doc, then after the meeting I take these notes, edit them a bit, and copy them to GitHub. This requires that I convert them from google doc to markdown which is always a bit painful.

I would like to implement a process which removes the need for conversion from google doc to markdown, or automates it better.

**Comment by wipfli** [comment]
Also automating or writing a checklist for notes publishing would be good. We publish them on GitHub, and announce them in slack and on maplibre.org

**Comment by HarelM** [comment]
Automating this would save time, I agree...
Please make sure the process you choose is simple for others to follow in the future, i.e. well documented.

**Comment by wipfli** [comment]
Good idea to document this, @HarelM. The notes taking and publishing might be documented as a checklist in the wiki. Checklists are something that @klokan suggested are helpful.

**Comment by wipfli** [comment]
That is actually a good idea. We could just stop sharing it with write access after the meeting notes are finalized.

**Comment by klokan** [comment]
It was administrativelly more pain - to always create a copy, new document and attach it to invite in the moment of invite - so we ended up with one long document where last meeting is always added - as it was faster to prepare.

**Comment by HarelM** [comment]
Yea, I totally understand. 😀

**Comment by wipfli** [comment]
We can actually just use https://workspace.google.com/marketplace/app/docs_to_markdown/700168918607 to convert google docs to markdown automatically. Why did I not check earlier... Anyway, I will write a checklist somewhere in the wiki about this.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre/wiki/Monthly-Meeting-Checklist
