### ISSUE TITLE
Implement a Request for Comment process

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#120]
We need a process to discuss and reach decisions, and then follow the decisions we take. We concluded that we need a process like Request for Comments (RFC) to discuss topics of limited scope and document the decisions we take. We can take inspiration for example from Rust https://github.com/rust-lang/rfcs or GDAL https://gdal.org/development/rfc/index.html.

**Comment by wipfli** [comment]
Ah interesting. Thanks @thehoneymad! What is the difference between PEPs and RFCs?

**Comment by HarelM** [comment]
I generally agree RFCs have bad reputation :-) but it doesn't have to be like http protocol RFCs. The initials stands for request for comments, it doesn't say it has to be finalized and fully technically solved 😀
Bottom line, we agree, this should be agile, open, dynamic, live and not rigid and rigorous.

**Comment by thehoneymad** [comment]
Sweet. I actually love ❤️ RFCs. :D Rigor is good, for long term continuous investment in an improvement.

As long as we can start with something easy, I think we should be okay. :)

**Comment by thehoneymad** [comment]
Adding related issue here for posterity. https://github.com/maplibre/maplibre-gl-native/pull/417

**Comment by thehoneymad** [comment]
I think to be pragmatic here, we can keep working on with what we have right now. Or we can give RFC a try. My wish here is to:

1. Try out one format, see how it fits.
2. Evolve as we go instead of waterfalling choices.

@wipfli how about we go with what we have right now which is KIP inspired? If we see this is not doing it for us, we can switch to RFCs?

**Comment by wipfli** [comment]
Yes, let's keep it as it is for now with the Design Proposal in Native.
