### ISSUE TITLE
Experience sharing framework

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#122]
The community together has a lot of experience with native mapping development. It would benefit everyone if we had a way of sharing our good and bad experiences. MapLibre seems to be the ideal place to share experiences publicly. We will set up a format with which people can share what worked for them and what didn't.

**Comment by maxammann** [comment]
Hm I think maybe the slack channel would be best for that with additional blog posts written by people. Or we could do weekly hangouts to discuss gpu stuff, or do short presentations.

**Comment by wipfli** [comment]
Let's share experience in the context of Design Proposals.
