### ISSUE TITLE
Make an Android release of MapLibre GL Native

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#133]
## Bounty Motivation

We did not have an Android release since December 2021. Would be great to release the improvements that went into the `main` branch since then.

## Bounty Amount

$100 (Size: S)

## Bounty Scope and Acceptance Criteria

To complete this bounty, the following things have to be done:

* Create or update an existing GitHub workflow which generates a release when a git tag matching `android-v*` is pushed.
* Secrets used in the release workflow are documented in MapLibre GL Native and are stored in clear-text in our password manager.
* The CHANGELOG for Android is updated and reflects the most important changes.
* A release `android-v9.6.0` is published on GitHub Releases and on Graddle.

## Show Your Support

Show your support for this Bounty with a :+1: if you like it...

Read more about Bounties here: https://github.com/maplibre/maplibre/wiki/Bounty-System.

**Comment by wipfli** [comment]
This is an example how the Bounty Issue template could look like...

**Comment by HarelM** [comment]
I think this is a great example.
I would also add a label of Small to allow better search.
Is this intended to be managed here or in the relevant repo?

**Comment by wipfli** [comment]
Let's manage Bounties in one place here in the maplibre/maplibre repo. If we find that it is unpractical, we can always move it to GL JS, Native, etc...

**Comment by HarelM** [comment]
Sorry, this is not the right place for this discussion, I'll move my comments to #125

**Comment by wipfli** [comment]
Closing this bounty example for now.
