### ISSUE TITLE
Onboarding repository maplibre-react-native

### ISSUE THREAD

**Issue by lseelenbinder** [maplibre/maplibre#134]
https://github.com/maplibre/maplibre-react-native (currently at https://github.com/lseelenbinder/maplibre-react-native)

## Motivation

There is no accepted OSS project for using MapLibre in React Native, despite a lot of demand for it. The best option is https://github.com/rnmapbox/maps, but they have formally announced discontinuing support for MapLibre.

This proposal would fork this project, specialize it to MapLibre (and drop support for the Mapbox SDK), and ensure that MapLibre developers using React Native as a solid option going forward.

Relevant Slack discussion: https://osmus.slack.com/archives/C02B2CBSNBU/p1665079311393029

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved for onboarding by:** @lseelenbinder @HarelM

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://osmus-slack.herokuapp.com/), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: @ianthetechie @achou11

#### Branches
- [x] The primary branch is named `main`.
- [x] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [x] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by wipfli** [comment]
Thanks for pushing this forward, I think it is a good idea. Can you also update the onboarding issue template? I am not on the Board anymore, but Harel and Birk are...

**Comment by wipfli** [comment]
Relevant discussion in the original repo is here: https://github.com/rnmapbox/maps/discussions/1680

**Comment by wipfli** [comment]
To be clear about the expectations regarding usage of donated resources for the react native wrapper: I think it would be best if this project started as a Hosted Project according to the definition in https://github.com/maplibre/maplibre/discussions/132. This means we host the project in the MapLibre umbrella but are not spending donated resources on it initially.

**Comment by HarelM** [comment]
@lseelenbinder besides forking it, do we have people who would like to maintain it as well?

**Comment by lseelenbinder** [comment]
Yes, a few mentioned willingness in Slack, and there seems to be a lot of general interest across the community, so I think we should acquire a few more.

**Comment by lseelenbinder** [comment]
I believe those that would be able to maintain initially are @achou11 and @ianthetechie.

**Comment by ansarikhurshid786** [comment]
It is really good to have separate from mapbox. i will also support.

**Comment by HarelM** [comment]
Great!! Thanks for stepping up!

**Comment by ianthetechie** [comment]
Thanks for the initiative on this @lseelenbinder!

**Comment by ahmedkhelifi** [comment]
This is inevitable!

**Comment by ianthetechie** [comment]
I don't know if it's been announced in the last two channels, but otherwise it's complete.

**Comment by wipfli** [comment]
@ovivoda can you add the announcement to our agenda for the next monthly meeting?

**Comment by wipfli** [comment]
@ianthetechie to announce the maplibre-react-native repo on Twitter, we can create a short post on maplibre.org/news. For that you can have a look at this announcement: https://github.com/maplibre/maplibre.github.io/tree/main/content/news/2023-01-12-grab-talk-khmer 

Are you interested in making a 2 paragraph news announcement, @ianthetechie?

**Comment by ianthetechie** [comment]
Sure, I can do that @wipfli. Gimme a few days ;)

**Comment by ovivoda** [comment]
@wipfli I added this to the agenda of the meeting on 8'th of February
