### ISSUE TITLE
Social media posting rules

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#143]
We have a discussion thread for posting messages on social media (Twitter and LinkedIn) at https://github.com/maplibre/maplibre/discussions/105, but it is a bit unclear if a post requires an approval and if yes, by whom.

Define some rules for social media posts.

**Comment by HarelM** [comment]
I agree, I think two board members approval is enough, I'm not sure majority is needed here, but we can also go for majority as well...

**Comment by wipfli** [comment]
Approval from 2 Board members sounds go to me.

**Comment by lseelenbinder** [comment]
2 is fine with me.
