### ISSUE TITLE
Onboarding repository navigation sdk iOS

### ISSUE THREAD

**Issue by Svantulden** [maplibre/maplibre#171]
https://github.com/maplibre/maplibre-navigation-ios (currently at https://github.com/flitsmeister/maplibre-navigation-ios)

## Motivation
Just like [the Android counterpart](https://github.com/maplibre/maplibre-navigation-android) that we donated to the Maplibre project, this SDK is a fork of the last Mapbox Navigation SDK version that is open-source. We’ve removed Mapbox telemetry and added small features like an improved automatic rerouting algorithm, customisation of SDK-drawn route polyline styles and a spam filter for routing calls. It uses the Maplibre Native SDK for iOS as the map powering the UI within this SDK. 

We think it could contribute to the Maplibre open-source project for iOS apps that want a simple stepping stone to develop navigation features. Currently we use this SDK ourselves in production for ~1,5 million active iOS users of our app. 

Relevant Slack discussion: https://osmus.slack.com/archives/C02B2CBSNBU/p1667981809322459

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved by:** @HarelM @birkskyum 

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://osmus-slack.herokuapp.com/), etc*
- [x] `/LICENSE.md`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: < @SjoerdPerfors & @Svantulden >

#### Branches
- [x] The primary branch is named `main`.
- [x] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [x] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [x] Grant admin rights to the board members (Currently @birkskyum )

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by HarelM** [comment]
LGTM.

**Comment by birkskyum** [comment]
Thanks for the generous contribution.

**Comment by Svantulden** [comment]
Thanks for looking at this! 

We've setup CI via Github Actions that runs on PR's and is needed to pass before merging. Also added you (@birkskyum ) as admin to the repository to move it.

**Comment by birkskyum** [comment]
We should be all set now. Super excited about this nice repo joining the org - I believe it's the first swift library.
