### ISSUE TITLE
Checklist for on-boarding new people in contracting roles

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#176]
Make a checklist in the wiki for things that have to be done when on-boarding new people in contracting roles. This should include

  * time tracking setup
  * access to repositories on GitHub
  * announcement at news blog

**Comment by wipfli** [comment]
@ovivoda since you are onboarding now, can you compile the items that you see?

**Comment by ovivoda** [comment]
@wipfli here it is what I have so far, but I will keep updating this with new things that will pop-up

- time tracking setup
- announcement at news blog
- access to repositories in GitHub
- include the person into the right Slack channels
- GitHub Projects guide on creating tasks. TO be refined
- guide on work methodology. TO be refined
- hand over onboarding material. Eg. introduction to MapLibre project, a bit of history, architecture documents, etc... TO be collected/defined
- setup objectives/goals

**Comment by wipfli** [comment]
Will put into wiki page

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre/wiki/Maintainer-Onboarding-Checklist
