### ISSUE TITLE
JavaScript CDN usage

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#196]
Find usage statistics of MapLibre GL JS on CDNs like unpkg.org

**Comment by wipfli** [comment]
@HarelM can you find have a look where we can find such statistics and share the link here?

**Comment by HarelM** [comment]
Can you clarify a bit more what you need?

**Comment by wipfli** [comment]
Some downlaod statistics of the maplibre-gl package from the most common cdns. I don't know how relevant this is since most people probably build with npm, but we might get some insights when people directly include the package as a run time loaded package.

**Comment by HarelM** [comment]
I'm sorry to say I have no clue how to do that.
I've tried poking around in unpkg, but I don't see any statistics anywhere.
Did you have something else in mind?

**Comment by wipfli** [comment]
Never mind in that case! I think most users are anyway on npm...
