### ISSUE TITLE
Find websites using MapLibre GL JS

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#197]
Find scraping service for finding which websites use MapLibre GL JS

**Comment by wipfli** [comment]
Maybe something like this:

https://www.similartech.com/technologies/mapbox

![image](https://user-images.githubusercontent.com/53421382/214896605-9baac562-f62a-40ba-8070-954acbbbc951.png)

**Comment by wipfli** [comment]
https://trends.builtwith.com/websitelist/MapLibre-GL-JS/Historical

**Comment by wipfli** [comment]
Oha we have 0.04 percent market share in mapping:

![image](https://user-images.githubusercontent.com/53421382/214900257-a305ed55-0d7a-4667-b5b9-0aeb98a6a0fe.png)

https://trends.builtwith.com/mapping

**Comment by wipfli** [comment]
Or this one: https://www.wappalyzer.com/technologies/maps/maplibre-gl-js/

Notable user of MapLibre GL JS: MapQuest!

![image](https://user-images.githubusercontent.com/53421382/214903293-077e1c9a-5bb9-479b-acf2-eb1a262dc536.png)

**Comment by wipfli** [comment]
https://www.wappalyzer.com/technologies/maps/

![image](https://user-images.githubusercontent.com/53421382/214903577-f7d2c4de-ef4b-4fb8-b5c1-7c0dee5321aa.png)

**Comment by wipfli** [comment]
https://www.wappalyzer.com/technologies/maps/

![image](https://user-images.githubusercontent.com/53421382/214903756-00400368-c46e-49d4-a518-78c2f2af3b7d.png)

**Comment by ovivoda** [comment]
nice stats @wipfli !
