### ISSUE TITLE
Onboarding repository mbtileserver-rs

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre#21]
https://github.com/maplibre/mbtileserver-rs

## Motivation
Mbtileserver offers community an actively maintained tool to serve tiles optimized for MapLibre GL & native. In addition, having this project as part of MapLibre will allow community to prototype new experimental features:
* alternative tile formats such as [flatgeobuf](https://flatgeobuf.org/)
* variable max-zooms depending on location -- densely populated areas could have higher max-zoom
* alternative non-web-mercator projections and combined projections (sphere for low zooms, web mercator for high zooms).
* optimized font serving, possibly with dynamic range partitioning
* integrate maplibre-native or maplibre-rs to allow server-side tile rendering
* styling features with tighter connection with data, dynamic icons, ...
* ...

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved by:** @nyurik @wipfli

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to Slack for discussions, link to the main maplibre.org page, etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [ ] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: @ka7eh

#### Branches
- [x] The primary branch is named `main`.
- [x] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [x] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [x] Grant admin rights to the board members and automation accounts for packages [mbtileserver](https://crates.io/crates/mbtileserver)
  - ~[npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`~
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli` 

## Community
- [x] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by wipfli** [comment]
Thanks @nyurik! Can you share some motivation why this is a good repo for the MapLibre org?

**Comment by wipfli** [comment]
Looks good to me. Thanks!

**Comment by ka7eh** [comment]
This is taken care of in https://github.com/maplibre/mbtileserver-rs/pull/14.
