### ISSUE TITLE
Set up organization-wide labels for bounties

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre#211]
Since bounties are used for repositories across the maplibre GitHub organization, it would be great if we could set them up as [default labels](https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization).

This way we avoid that we have to set them up for each repo separately and we can keep the labels consistent as well.

Edit: Actually, on closer inspection, this only applies to *new* repositories.

**Comment by louwers** [comment]
I created the following labels. It would be good to keep it consistent across repos:

💰 bounty L
#4d4637

💰 bounty M
#b3aa99

💰 bounty S
#D8CDB5

**Comment by wipfli** [comment]
I added them, thanks @louwers!

**Comment by HarelM** [comment]
@wipfli where did you add them? I don't see them in the gl-js repo. I'm about to add them, let me know if I shouldn't...

**Comment by louwers** [comment]
@HarelM You can add them!

They only get created automatically for new repos.

**Comment by HarelM** [comment]
Done for gl-js repo.
