### ISSUE TITLE
Onboarding repository flutter-maplibre-gl

### ISSUE THREAD

**Issue by maxammann** [maplibre/maplibre#228]
https://github.com/m0nac0/flutter-maplibre-gl

## Motivation
Flutter is the most major cross-platform app framework, next to React Native.
Having the repository in MapLibre allows us to push urgent bug fixes.

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved by:** @nyurik @HarelM 

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://osmus-slack.herokuapp.com/), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/SECURITY_POLICY.txt`
    Add the text:
    ```
    For an up-to-date policy refer to
    https://github.com/maplibre/maplibre/blob/main/SECURITY_POLICY.txt
    ```
- [x] `/CONTRIBUTING.md`
- [ ] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: <@user>

#### Branches
- [x] The primary branch is named `main`.
- [ ] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [ ] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [ ] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [ ] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by ianthetechie** [comment]
Thanks for taking initiative on this @maxammann! I'd be happy to contribute to ongoing maintenance efforts.

For the board members: this package will ultimately be published to pub.dev so we'll need to set up an account over there. We should probably set up an account as a [verified publisher](https://dart.dev/tools/pub/publishing#verified-publisher).

**Comment by maxammann** [comment]
cc: @m0nac0 let us know why you chose to hold back a release to pub.dev :)

**Comment by wipfli** [comment]
Nice to see this coming together!

If we need a new account somewhere, please let me know. I can create it and store the credentials in our password manager...

**Comment by m0nac0** [comment]
There is no particular / really significant reason for not publishing on pub.dev, yet.
They don't allow login with e.g. Github, only with a Google account, and I would've wanted to use a separate, non-personal account for that, which I haven't set up, yet.

**Comment by nyurik** [comment]
:heavy_check_mark:  approve, thanks!

**Comment by HarelM** [comment]
Approved. Please make sure to change the relevant things in the repo according to the checkboxes here.

**Comment by wipfli** [comment]
@m0nac0 you should be able to transfer your repository to the MapLibre GitHub organization now. I granted you the respective privileges. Thanks for your work!

**Comment by m0nac0** [comment]
Thank you! Should I keep the repository name or rename it during the transfer?

**Comment by m0nac0** [comment]
Also to add another todo item: we should rename the references to the old repo url in the code and tell the users about the transfer (e.g. in  pinned issue and in the Readme). But at least I think nothing should break since GH should automatically redirect references from the old repo to the new one. ('m not sure though if that would still work if the repo is renamed again after the transfer, which is the reason I'm asking if I should rename the repo during the transfer.)

**Comment by wipfli** [comment]
In my experience the transfer will result in really good redirects for all urls that point to the old repo

**Comment by m0nac0** [comment]
Ok, the transfer is done (might take a few minutes to fully complete it)

**Comment by wipfli** [comment]
@m0nac0 I made you an admin of this repository now. You are free to add other people and grant them write access or admin access as you think is suitable. Would be nice if you could announce in the maplibre slack channel if you add new people, like that we can welcome them a bit...

![image](https://user-images.githubusercontent.com/53421382/229792784-b8e24649-eddf-45af-87da-30c3475c3478.png)

**Comment by m0nac0** [comment]
Thank you, I'm happy to be on board and that this is working out!

**Comment by wipfli** [comment]
There are a bunch of open tasks. @mariusvn are you interested in helping complete them?

**Comment by mariusvn** [comment]
Hello ! It would be a pleasure to help as well !

**Comment by wipfli** [comment]
Great, thanks @mariusvn! I guess then the first step would be that the licensing and the special files section get all the ticks. Let me know if you have any questions...

**Comment by mariusvn** [comment]
Other than changing the date and the author organisation, does the liscence changes ? It is currently in BSD-3 liscense and lists the dependencies from `flutter-mapbox-gl`, `MapLibre GL native`, `MapLibre GL JS`, `Contains code from mapbox-gl-js v1.13 and earlier` liscense, `glfx.js` and `Contains a portion of d3-color https://github.com/d3/d3-color` liscense. Should I add something else ?

**Comment by mariusvn** [comment]
Added a bunch of files asked here in PRs of the repo

**Comment by m0nac0** [comment]
I already changed most settings before the transfer and @mariusvn kindly updated the "special files", so if I'm not mistaken, the only missing items are issue/PR templates, the personal branches and the announcements, right?

**Comment by maxammann** [comment]
And the pub.dev release :) I might get to it this week.

**Comment by ianthetechie** [comment]
I noticed that this repo should probably be transferred as well: https://github.com/m0nac0/flutter-maplibre-podspecs

**Comment by m0nac0** [comment]
I'd like to change the settings to not require a review before merging a PR for now, since I'm the only maintainer and I can't approve my own PRs. Is that okay?

**Comment by HarelM** [comment]
I maintain ngx-maplibre alone... It's OK I think...

**Comment by mariusvn** [comment]
It's your choice, im available if needed

**Comment by HarelM** [comment]
What is missing here in order to close this issue?

**Comment by josxha** [comment]
@HarelM Some update on the onboarding process:
- [x] The repo has Pull Request and Issue Templates in /.github dir.
- [ ] [Features] Enable Preserve this repository.
  - Can't see or edit this setting, can someone please check this? https://github.com/maplibre/flutter-maplibre-gl/settings
- [x] [Pull Requests] Community is encouraged to use squash merge. Disable other merge types if possible.
- [ ] [Pull Requests] Enable Automatically delete head branches.
  - I don't think that this is enabled and I don't have the permissions to change it.
- [ ] The repo has at least one admin who is ideally not part of the Governing Board: <@user>
  - Maybe @m0nac0? But I can't check, can someone with the required permissions please check on this? https://github.com/maplibre/flutter-maplibre-gl/settings/access
- [x] Set up branch rules to require CI pass and an approval before merge.
- [x] The repo must not have any personal branches.
- [x] Repo has a proper GitHub description and an optional web site
  - No website but a README with many information and hosted API docs at https://pub.dev/documentation/maplibre_gl/latest/
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] Grant admin rights to the board members and automation accounts for packages
  - Currently only Bart Louwers and the maintainers have been added to pub.dev. 
- [x] The new repo has been announced in the #maplibre OSMUS slack channel.
  - Yes, in https://osmus.slack.com/archives/C01G3D28DAB/p1680611746696389
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
  - Don't know
- [x] The new repo has been announced in the @maplibre twitter.
  - Indirectly via the 03/23 newsletter https://maplibre.org/news/2023-04-14-maplibre-newsletter-april-2023/

**Comment by HarelM** [comment]
I see that the repo was transferred. I've looked in the settings and it looks fine. 
I'm closing this issue. Enjoy coding!
