### ISSUE TITLE
Governing Board elections 2023

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#245]
Last year we did the Governing Board elections during FOSS4G at the end of August 2022. This year, FOSS4G will be 2 months earlier and I suggest that we do the elections only after 1 year independently of the FOSS4G date. So this year's Governing Board election will happen again at the end of August. More details with dates and deadlines will follow.

**Comment by wipfli** [comment]
#265

**Comment by wipfli** [comment]
Let's start fixing some dates:

- Governing Board Elections will take place on **Thursday, August 24th, 2023**
- Deadlines for changes to the Charter, adding new Voting Members, and Board candidate registration are defined in the Charter and derive from the Governing Board election date.

**Comment by nyurik** [comment]
@wipfli or @duje we urgently need to start publicising this, together with the deadlines:
* timeline to add new members
* timeline to nominate board members and publish nominee statements
* timeline for any votings

**Comment by wipfli** [comment]
Yes, thanks for the reminder, @nyurik!

**Comment by duje** [comment]
https://github.com/maplibre/maplibre/issues/265
