### ISSUE TITLE
Publish newsletter

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#257]
Write a newsletter April and publish it on our news website.

- Ping the relevant people to get information about what has happened in MapLibre GL JS / Native since the publication of the March newsletter.
- Look at news posts/tweets/slack announcements since the March newsletter and summarize them.
- Create a new section about the status of the Metal migration. Some questions we might want to address are:
  - What has been completed so far? 
  - What are breaking changes? 
  - What are important decisions? 
  - Where do we stand in the sequence of pull requests defined in the design proposal?
- In sync with the newsletter publication we should write a status update in https://maplibre.org/roadmap/metal

**Comment by wipfli** [comment]
Let's aim to publish the newsletter within one week of the monthly meeting, i.e. until next Wednesday

**Comment by ovivoda** [comment]
I started to gather the topics for each of the MapLibre GL JS / Native / Metal sections.
