### ISSUE TITLE
Write a thank-you letter template

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#263]
When individuals and companies sponsor MapLibre, we would like to show our gratitude with a thank-you letter. Write a template for such a letter.

**Comment by wipfli** [comment]
Write one for komoot.

**Comment by duje** [comment]
In consultation with the Governing Board and you @wipfli, on who is to sign every next Thank-you letter in the future.

**Comment by wipfli** [comment]
MIERUNE letter is out. Write letter for komoot, let @lseelenbinder print and sign it in the name of the Governing Board (we will loop though the board members...)

**Comment by duje** [comment]
in touch with Luke
