### ISSUE TITLE
Bounty system improvements

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#264]
Communicate that people/companies can request more than the pre-approved budgets for bounty directions.

Go through all communication (website, wiki).

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre/issues?q=is%3Aissue+is%3Aopen+label%3A%22bounty+direction%22

**Comment by wipfli** [comment]
https://maplibre.org/roadmap/step-by-step-bounties-guide/

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre/wiki/Bounty-System

**Comment by wipfli** [comment]
Make a news post https://maplibre.org/news/ about possibility to suggest large bounties

**Comment by wipfli** [comment]
https://opencollective.com/maplibre/transactions add paid bounties to developer pool https://github.com/maplibre/maplibre/wiki/Developer-Role#current-role-holders-developer-pool

**Comment by wipfli** [comment]
Thanks for the suggestion, @duje. I think the codeowners file is redundant because we already have the project tiers in https://github.com/maplibre/maplibre/blob/main/PROJECT_TIERS.md#tiers and the maintainers ensure that issues get answered in the core repositories.

**Comment by wipfli** [comment]
But what would be good is some communication channel to submit epics for bounties, i.e., a proposal for work which is composed of multiple bounties.

**Comment by duje** [comment]
Epic for Bounties means multiple tickets that add up to a larger solution. I will draft the section "Budget Increase" in https://github.com/maplibre/maplibre/wiki/Bounty-System about details that will have to be handed in by the Community to request a higher budget for a Bounty Direction which are listed in https://github.com/maplibre/maplibre/issues?q=is%3Aopen+is%3Aissue+label%3A%22bounty+direction%22.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre.github.io/pull/166
