### ISSUE TITLE
Onboarding repository Mapbox Directions SDK

### ISSUE THREAD

**Issue by KasparElmans** [maplibre/maplibre#278]
https://github.com/maplibre/maplibre-directions-swift (currently at: https://github.com/flitsmeister/mapbox-directions-swift/)

## Motivation
From XCode 14.3 and on, the minimum deployment target for a framework and its dependencies need to be 12.0 or higher. The current Maplibre Navigation SDK uses a couple of dependencies that still use 8.0 as a minimum, this is one of them. Therefore we needed to fork this dependency and upgrade it to support iOS 12.0.

The latest version of Mapbox Directions SDK has been converted from Objective-C to Swift. In the Maplibre Navigation SDK we still use a lot objective-C. Upgrading to the latest Mapbox Directions SDK exposes a lot of issues and would result in a big change. For just upgrading the version number this is out of scope. Therefore we chose to fork the repo and upgrade the version number. 

## What have we changed

Upgrade iOS version from 9.0 to 12.0.
Upgraded Polyline SDK from v4.2.0 to v5.1.0.
Removed private cartfile.

## Acceptance
- [ ] Any two board members must agree to accept a new repository.
  **Approved by:** <@user1> <@user2>

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://slack.openstreetmap.us), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/SECURITY_POLICY.txt`
    Add the text:
    ```
    For an up-to-date policy refer to
    https://github.com/maplibre/maplibre/blob/main/SECURITY_POLICY.txt
    ```
- [x] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [ ] The repo has at least one admin who is ideally not part of the Governing Board: <@user>

#### Branches
- [x] The primary branch is named `main`.
- [-] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [x] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [-] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by louwers** [comment]
Not sure how I feel about this one either...

Mapbox Directions SDK is also still permissively licensed and works with OSRM and Valhalla, so it's not like it's tied to some proprietary Mapbox interface that we don't control.

We plan to move from Objective-C to Swift too long term (cc @birkskyum ) so if we fork a much older version of this library which has a lot of Objective-C in it seems counter-productive.

Maybe it's true that 'big changes' are needed in the MapLibre Navigation SDK to get it to work with a newer version of this library, but when we onboard a repository into the MapLibre org we want that repository to be thrive in the long term whereas I have the feeling nobody is going to maintain an outdated fork that happens to be a dependency of the Navigation SDK.

My suggestion would be to pin this dependency to an older version maintained & released somewhere else, but not onboard it for the sake of onboarding it.

**Comment by birkskyum** [comment]
It looks like this has a quite limited amount of Obj-C
<img width="316" alt="Screenshot 2023-05-15 at 16 17 22" src="https://github.com/maplibre/maplibre/assets/74932975/ea6b14e9-5a53-487c-9d6c-fd345b72dacf">

To what extend is it permitted to use these API's with non-mapbox clients (Mapbox Directions API / Mapbox Map Matching API)?

**Comment by KasparElmans** [comment]
> My suggestion would be to pin this dependency to an older version maintained & released somewhere else. And plan to put in the work to use the more recent Swift-only version (and fork that if needed). Not onboard it for the sake of onboarding it.

So would it be okay to host this version at Flitsmeister? Until there is a valid update to a newer version?

**Comment by louwers** [comment]
> > My suggestion would be to pin this dependency to an older version maintained & released somewhere else. And plan to put in the work to use the more recent Swift-only version (and fork that if needed). Not onboard it for the sake of onboarding it.
> 
> So would it be okay to host this version at Flitsmeister? Until there is a valid update to a newer version?

I had a chat about this with @lseelenbinder and @birkskyum and yes, that seems like a good option. But let's explore using Mapbox Directions for Swift or a different library altogether (cc @ianthetechie ).
