### ISSUE TITLE
Policy for viewing pre-fork mapbox issue content

### ISSUE THREAD

**Issue by ZeLonewolf** [maplibre/maplibre#293]
### Problem statement
Some collaborators are unwilling to read issue content from pre-fork mapbox-gl issue repositories for fear of copyright infringement. However, the pre-fork issue content and the discussions within them remain relevant context for proposed features and contain valuable design work that can be leveraged. Remaining ignorant of these past discussions makes us less effective as a project and invites conflict when evaluating proposals without this context.

As an alternative, it has been suggested that contributors summarize those discussions and/or copy them from the mapbox repositories. However, it is unclear why it's legally acceptable for some collaborators to view this content but unacceptable for others. If it's not okay for a maintainer to view old content for copyright reasons, then it's not okay for an ordinary contributor either.

Additionally, consider that Mapbox might take this issue content offline at anytime, which risks a permanent loss of this content if not archived in some way.

### Proposal

I request that the maplibre team clarify what is allowed with regard to interacting with mapbox-gl issue repositories.

If the maplibre team feels that it is inappropriate or too risky to view this content or link to it in issues and PRs, I propose to develop and openly publish scripts to extract mapbox-gl pre-fork issue content and re-host it in a public location that all can access as a "safe to view" form (either in a new github repo or in some other static form). The code would be open source so all can verify that it is only gathering pre-fork content. However, because this is non-trivial work, I will not take this on unless the maplibre team feels that it would solve the problem and that maintainers would be willing to view the archived content in this form.

### Team perspectives

Below are a collection of comments by project members related to this issue:

**Harel Mazor**:
"you can't expect the maintainers team here to look into mapbox issues (even old ones), as looking into them might increase the risk of infringing copy right laws (which is, from my point of view, the biggest risk to this project). So if you would like to discuss something, please open a separate issue in the relevant repo and copy/rewrite the relevant text." [1]

**Bart Louwers**:
"We need to take extreme caution not to violate Mapbox' copyright.
You can create an issue describing your wishes, but don't include any proprietary implementation or design details that you are aware of. If you have looked at the code you also cannot make any code contributions." [2]

**Luke Seelenbinder**:
"I would prefer linking back to the original discussion, where it makes sense." [3]

**Bryan Housel**:
"This doesn’t make sense to me .. Issue content falls under “user generated content”, it’s not licensed like the content of the repo." [3]

**Oliver Wipfli**:
"I think it is best if we keep discussions self-contained in the MapLibre repositories because then people who follow the MapLibre discussions will remember and be able to find duplicate issues or useful old links faster. If we want to keep the discussions self-contained but still want to profit from past context, we can summarize the main message of a past thread and possibly add a link to it a bit like a citation. I think it is important that we build up the knowledge in our own community and keeping discussions self-contained can help with that." [3]

[1] https://github.com/maplibre/maplibre-style-spec/discussions/36#discussioncomment-5203810
[2] https://osmus.slack.com/archives/C01G3D28DAB/p1680691125017299
[3] https://osmus.slack.com/archives/C01G3D28DAB/p1678040252948539?thread_ts=1678040151.268119&cid=C01G3D28DAB

I have added this to the agenda for the 14 June 2023 technical steering committee.

**Comment by FelixFaassen-TomTom** [comment]
Hi,

I just did a small informal check with our legal team based on how issues content is licensed. Maybe it can help this discussion.

Under Article 6 of the Github Terms of Service ([6. Contributions Under Repository License](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users)), it is stated that whenever you add Content to a repository containing notice of a license, you license that Content under the same terms. “Content” is defined broadly, and it seems to include also “User-Generated Content” such as issues.
 
However, if you have a separate agreement to license that Content under different terms, such as a contributor license agreement, that agreement will supersede. 

Is there a contributor license agreement that applies to the issues in the mapbox based repo's?
 
Logically speaking, if there is no separate license covering the issues, all content added to the repository should follow the same license as that applies to the repository itself.

Let me know if this makes sense / is helpful or not.

**Comment by louwers** [comment]
Thanks for summing up the different perspective.

To summarize: linking to pre-fork PRs or issues for some _additional_ context is probably not a problem. At the same time, issues on MapLibre repos should be self-contained i.e. contain all necessary information without the need to dig through old Mapbox issues.
