### ISSUE TITLE
Governing Board Elections 2023

### ISSUE THREAD

**Issue by duje** [maplibre/maplibre#298]
As mentioned in our [Newsletter in May](https://maplibre.org/news/2023-05-18-maplibre-newsletter-may-2023/), the Governing Board Elections 2023 will take place August 24th, 2023.

Here you find the relevant dates and deadlines leading up to the election as defined in the [MapLibre Charter](https://github.com/maplibre/maplibre/blob/main/CHARTER.md).

## Timeline

* **July 27th, 2023**
  * Changes to the Charter can be proposed by Voting Members until: Thursday, July 27th, 2023
* **August 10th, 2023**
  * Registrations for [Candidates for the Governing Board](https://github.com/maplibre/maplibre/discussions/299) close on: Thursday, August 10th, 2023
* **August 17th, 2023**
  * Nominations for [new Voting Members](https://github.com/maplibre/maplibre/issues/300) close on: Thursday, August 17th, 2023
* **August 21st, 2023**
  * Approval of new Voting Members take place on: Monday, August 21st, 2023
* **August ~~24~~ 30th, 2023**
  * Governing Board Elections take place on: Wednesday, August  ~~24~~ 30th, 2023

## Registration of Governing Board Candidates

If you would like to become a Governing Board member, please [register](https://github.com/maplibre/maplibre/discussions/299) yourself for the election until Thursday, August 10th, 2023.

## Nomination of new Voting Members

Existing Voting Members can nominate new Voting Members  until Thursday, August 10th, 2023 in this Issue: https://github.com/maplibre/maplibre/issues/300 

## Approval of new Voting Members

The existing Voting Members will vote on approving the new Voting Members on Thursday, August 17th, 2023 via an OpaVote poll.

## Governing Board Elections

All the Voting Members (existing and approved new ones) will elect the new Governing Board on Wednesday, August 30th, 2023 via OpaVote poll.

## Changes to the Charter

The Voting Members will also vote on proposed changes to the Charter via OpaVote poll on Thursday, August 24th, 2023.

Edit August 14th, 2023: The deadline for nominating new Voting Members was moved from August 10th, 2023 to August 17th, 2023 because only as small number of Voting Members was nominated. The approval of new Voting Members was also moved to a later date. ~~However, the Elections will still take place on August 24th, 2023.~~

Edit August 22nd, 2023: The Governing Board election poll has now been sent the the Voting Members. We moved the date of the Election to Wednesday, August 30th, 2023, because we want to give people sufficient time to fill out the voting poll. If you are a Voting Member and did not get an email, please get in add a note in the thread below. We can send additional emails to alternative email addresses.

**Comment by birkskyum** [comment]
I don't understand why the Charter is mentioned in relation to the Board election. The only reason the Charter was altered near the same time as the last Board election was to create it in the first place.

**Comment by birkskyum** [comment]
The result of the Governing Board Election can be found here:

https://www.opavote.com/results/5696407649386496

The Governing Board is unchanged, with the elected members being:

- Harel Mazor
- Yuri Astrakhan
- Birk Skyum
- Luke Seelenbinder
- Petr Pridal

Substitute - In case a board member steps down over the next year, the seat will be granted to:

- Jonah Adkins
