### ISSUE TITLE
Nomination of New Voting Members 2023

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#300]
Existing Voting Members can nominate new Voting Members, see the [MapLibre Charter](https://github.com/maplibre/maplibre/blob/main/CHARTER.md).

Voting Members should have made a non-trivial contribution to MapLibre.

If you are a Voting Member and would like to nominate someone, do the following:

* Ask the person if they want to be Voting Members
* Ask them if it is OK to publish their employer, name, github handle here

If both are positive, then you can nominate the person here in this thread to become a Voting Member. Please indicate the GitHub Handle, Name, and Employer. Note that at most 10 percent of the Voting Members can come from one company.

Example: 

`I would like to nominate: @pramilk, Pramil Kuchhal, Microsoft, contributed to MapLibre GL JS`

Nominations for new Voting Members close on Thursday, ~~August 10th, 2023~~ August 17th, 2023. Edit: We extended the deadline to allow for more nominations. The election date will still be August 24th, 2023.

## For nominees: share your email

If you have been nominated, we will need to collect your email address for the OpaVote voting system. Please fill out this form with your email address if you have been nominated: https://forms.gle/QDRfVNieAWaotNfdA

Note: if the google form does not work for you, please send your email to Oliver Wipfli via the Slack channel in a direct message.

**Comment by wipfli** [comment]
I would like to nominate: @thehoneymad, Swagata Prateek, AWS, for contributions to MapLibre Native

**Comment by lseelenbinder** [comment]
I would like to nominate: @ianthetechie, Ian Wagner, Stadia Maps, for contributions to React Native and Navigation SDKs.

**Comment by lseelenbinder** [comment]
I would like to nominate: @danielgard, Daniel Gard, komoot, as a sponsor of MapLibre.

**Comment by mojodna** [comment]
I would like to nominate @mwilsnd, Marc Wilson, Meta, for contributions to MapLibre Native.

**Comment by HarelM** [comment]
I would like to nominate the following contributors:
@neodescis @ZeLonewolf @drwestco @ChrisLoer @kajkal @visitskyworld @pramilk @HandyMenny @rotu @ptomulik @ibesora @zhangyiatmicrosoft @jleedev @Pessimistress @IvanSanchez @tordans @smellyshovel @kevinschaul @acalcutt @VehpuS @ambientlight @kircher1

**Comment by ZeLonewolf** [comment]
I believe I am already a voting member, unless this is intended to be an annual process?

**Comment by HarelM** [comment]
I wasn't sure, so I might have nominated people who are already eligible.

**Comment by birkskyum** [comment]
@ZeLonewolf , yes you are already a voting member.

**Comment by birkskyum** [comment]
I'd like to nominate @louwers , for a huge effort on Native

**Comment by wipfli** [comment]
We will need the email addresses of all new voting members for opa vote, the voting system. Also we will need to know the company because of the 10 percent limit.

**Comment by birkskyum** [comment]
hmm, should we set up a form where nominees can fill in these contact details?

**Comment by wipfli** [comment]
I would like to nominate:

* @boldtrn, Robin from ???, for maintaining the android navigation plugin
* @ovivoda, Ovi Voda (freelance), for maintaining MapLibre Native
* @marcregan, Marc Regan from Meta, for sponsorship and Metal coordination work
* @jonahadkins, Jonah Adkins from Meta, for sponsorship
* @stefanschaller, Stefan Schaller from ??, for working on the flutter bindings
* @ianthetechie, Ian Wagner from Stadia Maps, for maintaining MapLibre React Native
* @m0nac0, ?? from ??, for maintaining the flutter bindings
* @JulianBissekkou, Julian Bissekkou from ??, for helping with the flutter bindings
* @Fabi755, ?? from ??, for helping with the android navigation plugin
* @sarahsporck, Sarah Sporck from ??, for helping with MapLibre React Native
* @JonasVautherin, Jonas Vautherin from ??, for contributions to Native
* @tdcosta100, Tiago Costa from ??, for contributions to Native
* @FynnGodau, Fynn Godau from ??, for contributions to Native
* @SiarheiFedartsou, Siarhei Fedartsou from ??, for contributions to Native
* @typebrook,  Hsieh Chin Fan from ??, for contribution to Native
* @alanchenboy, Alan Wei Chen from Grab Maps, for contributions to Native
* @mariusvn, Marius Van Nieuwenhuyse from ??, for contributions to the flutter bindings
* @sjg-wdw, Steve Gifford from WetDogWeather, for works on Metal in Native
* @tjulien, Tim Julien from Radar, for sponsoring MapLibre
* @mactrem, Markus Tremmel from Rhode & Schwarz, for contributions to a new tile format
* @Miguel-Sanches, Miguel Sanches from ??, for contributions to maplibre-gl-directions

If I missed anyone, please let me know and I will add you.

**Comment by wipfli** [comment]
Deadline for nominations is today. To participate in the vote, we need the email addresses of new voting members. You can share your email address here: #312

**Comment by wipfli** [comment]
Thank you for all the nominations. The existing Voting Members are now confirming the nominated Voting Members via an OpaVote poll. This poll will end on Monday, August 21st, 2023 at 17:00 CEST.

While the [MapLibre Charter](https://github.com/maplibre/maplibre/blob/main/CHARTER.md) does not specify what threshold should be used in the confirmation of new voting members, I suggest that we should have a yes majority of the people who participate in the vote. This is similar to how changes to the Charter are handled.

**Comment by lseelenbinder** [comment]
> While the [MapLibre Charter](https://github.com/maplibre/maplibre/blob/main/CHARTER.md) does not specify what threshold should be used in the confirmation of new voting members, I suggest that we should have a yes majority of the people who participate in the vote. This is similar to how changes to the Charter are handled.

I believe a simple majority is the intended implication. Perhaps we should add that as a vote in the near future to clarify it for the future?

**Comment by wipfli** [comment]
Sounds like a good idea, @lseelenbinder. Let's open a tracking issue for charter improvements...

**Comment by birkskyum** [comment]
@JannikGM that does seem a lot more reasonable, and I find the current system very problematic too. The only filter we currently have is who gets nominated, which is a good start, but in no way sufficient as there is no review. As soon as someone is nominated it's effectively a guaranteed addition to the voter pool with all of us voting "yes" on unknown peers, rendering this vote utterly pointless, and with no way for the community to surface important information.

**Comment by birkskyum** [comment]
Due to the weekend, the vote will stay open 2 days longer, so until Aug 23rd 17:00 CEST.
