### ISSUE TITLE
Onboarding repository martin

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre#31]
[urbica/martin](https://github.com/urbica/martin) &rarr; [maplibre/martin](https://github.com/maplibre/martin)

## Motivation
[Martin](https://github.com/urbica/martin) is one of the most well known tile servers with 83 forks and 741 stars.  Martin was written by @stepankuzmin, who has expressed desire to join MapLibre and continue working on it. This project is fairly up to date with web serving code, and uses PostgreSQL as the only data store.

Moving this project to MapLibre would help us combine it with the [maplibre/mbtileserver-rs](https://github.com/maplibre/mbtileserver-rs), as was discussed in https://github.com/maplibre/maplibre/discussions/30.

### Goals for Martin
*Copied from the last section https://github.com/maplibre/maplibre/discussions/30*
* refactor Martin's PostgreSQL datastore code into a separate lib, possibly using some of T-Rex code as well.
* refactor mbtileserve-rs .mbtiles code into a separate lib
* enhance maplibre-rs to be able to render tiles accessible via the same interface
* Martin, maplibre-rs, and mbtileserve-rs (?) will use any of the data providers as needed.

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved by:** @nyurik @wipfli 

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [ ] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [ ] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://osmus-slack.herokuapp.com/), etc*
- [ ] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [ ] `/CONTRIBUTING.md`
- [ ] The repo has Pull Request and Issue Templates in `/.github` dir.
- [ ] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [ ] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [ ] **[Features]** Disable unused features like wiki.
- [ ] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [ ] **[Features]** Enable `Preserve this repository`.
- [ ] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [ ] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [ ] The repo has at least one admin who is ideally not part of the Governing Board: <@user>

#### Branches
- [ ] The primary branch is named `main`.
- [ ] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [ ] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [ ] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [ ] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`

## Community
- [x] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [x] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by wipfli** [comment]
Thanks @stepankuzmin for showing interest to move Martin to MapLibre and thanks @nyurik for taking the time to draft the onboarding.

Sounds like a nice idea to me. @stepankuzmin, would you see yourself in the role of a maintainer of Martin still in the future when it would be part of MapLibre?

**Comment by stepankuzmin** [comment]
Hey @wipfli, @nyurik 👋 

Thanks for starting this discussion! I want to maintain Martin, and I have some ideas for improvements :)
