### ISSUE TITLE
Missing Email Addresses of Voting Members

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#312]
We need the email addresses of the MapLibre Voting Members for the email voting system Opa Vote.

If you are a voting member and you already participated last year in the election, then nothing is to be done for you.

If you have been nominated to become a voting member in #300, then please fill out this form with you personal details: https://forms.gle/QDRfVNieAWaotNfdA

Note: if the google form does not work for you, please send your email to Oliver Wipfli via the Slack channel in a direct message.

**Comment by wipfli** [comment]
@METACEO you became a MapLibre Voting Member in 2022, however, we never got an email address of you. Can you fill out this form https://forms.gle/QDRfVNieAWaotNfdA and share your email address?

**Comment by HandyMenny** [comment]
> @kajkal, @HandyMenny, @kircher1, @sharkAndshark, @stuartlynn, @JonasVautherin
> 
> Unfortunately, I haven't found you on Slack.

yeah ,I am not in the osmus slack.
However, I have submitted the google form and made my email public on my github profile

**Comment by tdcosta100** [comment]
@duje, I sent my email in the form, did you receive it?

**Comment by neodescis** [comment]
DM'd you on slack. Thanks!

**Comment by sharkAndshark** [comment]
@duje Hi duje! I've DM you on slack. Have a good day : )

**Comment by upsicleclown** [comment]
@duje I had filled in mine via the form but my email is roxiestanciu12@gmail.com

**Comment by stuartlynn** [comment]
Hey @duje I filled out a form with mine a few days ago. Let me know if you didn't get it and I will do it again

**Comment by wipfli** [comment]
@kircher1 retracted the nomination to become a Voting Member, so we don't need their email address.
