### ISSUE TITLE
Onboarding repository [https://github.com/m0nac0/maplibre-gl-dart/]

### ISSUE THREAD

**Issue by JulianBissekkou** [maplibre/maplibre#313]
https://github.com/m0nac0/maplibre-gl-dart/

## Motivation
maplibre-gl-dart is only used for [flutter-maplibre-gl](https://github.com/maplibre/flutter-maplibre-gl) and we would like to move the repositories source into the flutter-maplibre-gl as described in https://github.com/m0nac0/maplibre-gl-dart/issues/2

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved by:** @HarelM @nyurik 

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] ~The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.~

## Special files
- [x] ~`/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://slack.openstreetmap.us), etc*~
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] ~`/SECURITY_POLICY.txt`
    Add the text:
    ```
    For an up-to-date policy refer to
    https://github.com/maplibre/maplibre/blob/main/SECURITY_POLICY.txt
    ```~
- [x] ~`/CONTRIBUTING.md`~
- [x] ~The repo has Pull Request and Issue Templates in `/.github` dir.~
- [x] ~The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)~
- [x] ~`/CODE_OF_CONDUCT.md`~
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

## Repo Settings
#### General page
- [x] ~**[Features]** Disable unused features like wiki.~
- [x] ~**[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).~
- [x] ~**[Features]** Enable `Preserve this repository`.~
- [x] ~**[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.~
- [x] ~**[Pull Requests]** Enable `Automatically delete head branches`.~

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: @m0nac0

#### Branches
- [x] ~The primary branch is named `main`.~
- [x] ~Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*~

## Miscelaneous
- [x] ~The repo must not have any personal branches.~
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] ~Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*~
- [x] ~CI automatically runs on all pull requests before merging using GitHub actions~
- [x] ~Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`~

## Community
- [x] ~The new repo has been announced in the `#maplibre` OSMUS slack channel.~
- [x] ~The new repo has been announced in the next monthly meeting of the Technical Steering Committee.~
- [x] ~The new repo has been announced in the `@maplibre` twitter.~

**Comment by JulianBissekkou** [comment]
Most of the things are unchecked because the current repository does not have most of the things. However flutter-maplibre-gl has all of those things and since we want to move the repo **into** flutter-maplibre-gl it should be fine.

**Comment by JulianBissekkou** [comment]
I striked through all the things that are only related for new repositories which was almost everything

**Comment by louwers** [comment]
@HarelM @birkskyum @nyurik @klokan @lseelenbinder 

This is not a new repo, but incorporating another repo into an existing repo. Not sure if board approval is required in this case. Let us know, looks good from my side.

**Comment by HarelM** [comment]
If the outcome is that we don't create or at a new package to a package manager, I don't think an approval is needed.
Nevertheless, this is approved from my point of view.

**Comment by nyurik** [comment]
lgtm

**Comment by louwers** [comment]
Thanks!

**Comment by JulianBissekkou** [comment]
Thanks for the approval, I am going to close this issue and we will move the code over as we described it.
