### ISSUE TITLE
Assign linux-builder to maplibre-native-qt

### ISSUE THREAD

**Issue by ntadej** [maplibre/maplibre#327]
Can `linux-builder` package be assigned to `maplibre-native-qt` so I can setup automatic updates?

See https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package

/cc @HarelM @birkskyum @wipfli

**Comment by birkskyum** [comment]
This is what I see

<img width="1151" alt="Screenshot 2023-09-18 at 13 58 25" src="https://github.com/maplibre/maplibre/assets/74932975/1f8f0e14-5232-4671-8efa-ea8e45f413bd">

I don't understand the context around this package. Was is prev made from maplibre-native/platform/qt, and is the split at it's final stage now?

**Comment by ntadej** [comment]
It's a container to make Qt builds compatible with the upstream Qt binaries.

**Comment by ntadej** [comment]
Not sure I understand your question about drawables, can you maybe open a ticket/discussion on that?

Is there any more information you need from my side for this to proceed?

**Comment by birkskyum** [comment]
I just noticed recent changes to the qt folder in the maplibre-native repo and the commit message was something about drawables

**Comment by birkskyum** [comment]
@louwers , are you on board with this?

**Comment by birkskyum** [comment]
I've linked the package.

**Comment by louwers** [comment]
@birkskyum Yes, makes sense!
