### ISSUE TITLE
void

### ISSUE THREAD

**Issue by abebeos** [maplibre/maplibre#349]

**Comment by HarelM** [comment]
That's an interesting approach. Thanks for sharing!
I think the main problem is that there are just too many places to communicate and I personally find it hard to remember where I posted stuff, this won't solve this obviously, but it might help see things in a faster way.
I usually just query the relevant repo for issues with the relevant labels, but that's probably just me :-)

**Comment by HarelM** [comment]
@wipfli let me know if you would like to organize this, I'm not sure about the ROI of this...

**Comment by abebeos** [comment]
> I'm not sure about the ROI of this...

It is not always about ROI, but about "sticking to standard-procedure" and kindness (help newcomers and evaluators that need to process many information).

At minimum, create projects for one or two dev-directions that have many issues (e.g. https://github.com/maplibre/maplibre/issues/189, https://github.com/maplibre/maplibre/issues/270, etc.), so you can experience the "live" look&feel.

**Comment by wipfli** [comment]
Thanks for suggesting the views in the mapmock repo @abebeos. I think we can improve many things around the bounty system and I'm happy to get your feedback.

Do you know of a github organization which has a really nicely organized bounty system that I could have a look at?

**Comment by abebeos** [comment]
> Do you know of a github organization which has a really nicely organized bounty system that I could have a look at?

Sadly not, because the bounty-systems have usually not the best processes themselves (and have fees).

 * bountysource.com had a casual process, only a `W-8BEN` was needed, and a paypal. But they went out of business, despite 10% fees (bounty worker side)
* https://console.algora.io/ is another bounty-system, but has too much process, is Stripe bound and charges quite some fees to the bounty-issuers (wasted money, in my opinion).

You could modify your current system by simply dropping some of the complexity and making it faster:

- No need to fill out a form and make a call.
- No need to list real-name in public
- Only bureaucracy: File data within Open-Collective, Invoicing
  - Personal data should stay non-public (even the real name)
  - Payouts should be once a week, max. once 2weeks

That should fix it.

**Comment by abebeos** [comment]
Just went through the open-collective invoicing process. **All is quite fine**, privacy is respected, too (handle in public, real name & private data non-public).

I'd say that if the Open-Collective payout-speed is high, and the fees low, then it outperforms any bounty-system i've worked with.

**Comment by abebeos** [comment]
And they have even a nice(!) github bound bounty process, ready to adopt:

https://docs.opencollective.com/help/contributing/development/bounties

**Comment by abebeos** [comment]
(extended this issue in order to avoid filing new ones. Please review original text)
