### ISSUE TITLE
Update MapLibre Native Bot GitHub app for iOS distribution

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre#354]
I want to use a fine-grained personal access token in a workflow to create a PR in another repository.

This is not enabled by default. Instructions to enable this can be found here:

https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization

**Comment by HarelM** [comment]
I find this problematic and I tried to avoid it as much as possible.
The main reason, is that a PAT is linked to a GitHub user and not an organization, and controlling it is a complicated.
Can you think of a way, maybe a bit more annoying, that won't require this?

For example, when I wanted to automate the release process of maplibre-gl I ended up creating an action that creates a PR and only when this PR is merged then the package is released. While this is possible in one go with PAT this approach removes its need.

**Comment by louwers** [comment]
Yes that is a good point @HarelM.

I could use the (organization level) GitHub App that we created and trigger a workflow in the other repo. https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event

The Actions permission would need to be added:

<img width="826" alt="image" src="https://github.com/maplibre/maplibre/assets/649392/36c1b592-2df8-4ff8-9f65-624395c8c116">

**Comment by HarelM** [comment]
Sounds better I think, where can I configure this?

**Comment by louwers** [comment]
@HarelM I think: MapLibre organization settings, then Developer Settings, GitHub Apps, MapLibre Native Bot.

**Comment by HarelM** [comment]
I believe it already has these permissions:
![image](https://github.com/maplibre/maplibre/assets/3269297/80c536f6-7deb-4843-b7c6-f09edaf66adc)

Do you need me to add it to another repo?

**Comment by louwers** [comment]
Yes please! This repo: https://github.com/maplibre/maplibre-gl-native-distribution

**Comment by HarelM** [comment]
Added, let me know if you need anything else.

**Comment by louwers** [comment]
I ran it manually once and it seems to work!
