### ISSUE TITLE
Call for Google Summer of Code 2024 Projects, Mentors & Contributors

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre#355]
We are looking for projects & mentors for [Google Summer of Code 2024](https://summerofcode.withgoogle.com/), which we want to join as a mentor organization.

We will submit project ideas from the community and a list of possible mentors. If you have a project idea, leave a comment with the following information:

1. Brief description of the project idea and the associated MapLibre project.
2. Expected time to complete the project. ~90 hour, ~175 hours or ~350 hours.
3. How hard is it? Could a (motivated) student complete it? Any prerequisite skills? Easy, medium hard.
4. If you would be available to mentor the project during a 12 week period, consisting of regular meetings with the (student) contributor and being available for questions.

If you want to participate as a contributor, feel free to already indicate your interest here so you will be notified.

If you don't have a project idea, but are willing to be a mentor for a MapLibre GSoC project, you can also leave a comment here.

## Mentors

- @ibesora - MapLibre GL JS
- @nyurik - Martin
- @louwers - MapLibre Native

### MapLibre GL JS

MapLibre GL JS is a mapping toolkit for the web written in TypeScript.

- [Sky shading](https://github.com/maplibre/maplibre/issues/355#issuecomment-1918805948)

### MapLibre Native

MapLibre Native is a mapping toolkit written in C++.

- [Improve performance of the geometry tile worker of MapLibre Native](https://github.com/maplibre/maplibre/issues/355#issuecomment-1919121924)

### Martin

[Martin](https://github.com/maplibre/martin) is a map tile server written in Rust, as well as a collection of tools to work with tile packaging and generation.

- martin user interface
  - https://github.com/maplibre/martin/issues/1120
  - https://github.com/maplibre/martin/issues/852
- improve Server caching
  - https://github.com/maplibre/martin/issues/1112
  - https://github.com/maplibre/martin/issues/1137
- Implement parser/encoder of the new tiling format - for now managed in [cov-tiles](https://github.com/mactrem/cov-tiles) repo

**Comment by lseelenbinder** [comment]
I wonder if something like `addProtocol` could be accomplished in a summer project?

**Comment by tordans** [comment]
Would https://github.com/maplibre/maplibre-gl-js/issues/1235 be something that fits in the scope of GSoC? And is there a mentor to support this?

**Comment by louwers** [comment]
@lseelenbinder You mean for Native? That sounds a bit too ambitious to be honest.

@tordans I think so, but we a description of the project as described above would be needed and of course a mentor.

---

Because the deadline for applying is February 6, 2024 and we need to go through our fiscal host, please respond before the end of January.

**Comment by ibesora** [comment]
**Project idea:** Implement atmosphere / sky shading 
**Expected time to complete the project:** ~90 hour
**How hard is it? Could a student complete it? Any prerequisite skills?:** Easy. Ideally, the student would have some experience with webgl
I would be available to mentor the student

**Comment by louwers** [comment]
@ibesora Very cool to have a project for MapLibre GL JS and that you are available as mantor.

If you want please write a few more details, because otherwise people unfamiliar with MapLibre (GL JS) may not understand the project. I am happy to extend your description as well.

**Comment by louwers** [comment]
**Project:** Improve performance of the geometry tile worker of MapLibre Native. To group layers we are calculating a [layoutKey](https://github.com/maplibre/maplibre-native/issues/1095) by computing a JSON object. This can likely be made more efficient!

Suggested plan of action:

1. Reading and understanding the relevant source code.
2. Getting the project to build locally.
3. Getting the project to run locally.
4. Getting the tests to run locally.
5. Running the relevant benchmark locally.
6. Making a plan to improve the performance.
7. Iterating on the plan to improve the performance (validating using benchmark and tests).
8. Making a pull request.
9. Incorporating feedback (or CI failures) pull request.
10. Getting your contribution merged and celebrating! 🎉 

**Expected time to complete**: ~90 hours
*Difficulty level**: Some with C++ will be very useful, but we can spend some time to get up to speed with C++ as well.

**Comment by louwers** [comment]
@nyurik Received the following message from Google. Could you please provide this information for each Martin project (in this issue)?

> This year we have noticed a large number of org apps are missing required information or having issues with project sizes. Please review your org app for these common mistakes that could result in your org app being rejected.
>
> 1. Project sizes need to be scoped to 90, 175 or 350 hours (you can not have a project that is 200 hours, or some other random number of hours).
> 2. Make sure your Project Ideas list is public so GSoC Google reviewers can access it.
> 3. Make sure your Project Ideas include the ALL of the required information below:
> 
> a) a project title/description b) more detailed description of the project (2-5 sentences) c) expected outcomes d) skills required/preferred e) possible mentors f) expected size of project (90, 175 or 350 hour – yes, 3 options starting in 2024). And if possible, an easy, intermediate or hard/difficult rating of each project. This helps the more inexperienced folks not get overwhelmed and they can focus on reviewing easy project ideas.
