### ISSUE TITLE
Set up github-repo-stats to track repository statistics

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre#358]
Under the Insights tab you can see pretty useful information about a repository. For example: how many pulls requests were made, how many times a repo was cloned, etc. This information is also exposed via the GitHub API.

Unfortunately, both the tab and the API only give out information for the past 14 days.

There is a GitHub Action that allows saving this information to a branch: https://github.com/jgehrcke/github-repo-stats

Then you can publish a GitHub page with long term statistics of a repo: https://jgehrcke.github.io/ghrs-test/jgehrcke/github-repo-stats/latest-report/report.html

I would like to set up this GitHub repo in a central repo that saves statistics for multiple GitHub repositories.

- `maplibre/maplibre-native`
- `maplibre/maplibre-gl-native-distribution` track usage of MapLibre Native (iOS)

If you also want statistics for a particular repo, e.g. `maplibre/maplibre-gl-js`, please respond here (cc @HarelM).

The question is: shall I add the workflow to this repository `maplibre/maplibre` or do we greate a new repository solely for gathering this data? E.g. `maplibre/repo-stats`.

**Comment by louwers** [comment]
I think making a new repo is the best approach, because we need to give this Action write access to the repo. It is also a bit cleaner to separate it from the rest.

**Comment by louwers** [comment]
@HarelM If you are not interested to have it set up for MapLibre GL JS, I will only set it up for the two repos I mention in the first post.

I would still like to have a separate repo so I only have to give permissions to the GitHub Action for that one repo.

**Comment by HarelM** [comment]
As said in Slack, the following I believe covers most of the analytics we need.
https://compass.gitee.com/
I've added maplibre repos and community a few month back.
If this is not the case I would consider defining a problem statement and selecting the right tool for the right job.
I think there was a rush to implement something although I don't understand what it needs to solve...
It might be just my observation/perspective.
Most of the things in our repos are public so I'm not sure I understand why a PAT is needed...
Not that I mind having a PAT somewhere, just haven't found a good reason to add this to our maintaining tasks...

**Comment by louwers** [comment]
@HarelM It is important to track (unique) clones as well for MapLibre Native.

https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-repository-clones

To access this data you need push access to the repository. It is not available to a public service like the one you shared.

**Comment by HarelM** [comment]
Can you describe the problem statement in a single sentence? I think I understand what you are saying, but I want to be sure.
Is the problem statement only relevant to iOS or is there a more generic problem statement?

**Comment by louwers** [comment]
We need more visibility on MapLibre Native usage, the non-public GitHub statistics will help here so we need to collect them.

**Comment by HarelM** [comment]
I think we have good visibility with npm download statistics for the web packages.
Doesn't iOS has a similar solution using cocoapods or something?

**Comment by louwers** [comment]
@HarelM Nope. There used to be: https://blog.cocoapods.org/Stats/

But it was abandoned because they could not find enough funding for data storage.

The Swift Package Index also doesn't keep track of any statistics.

**Comment by HarelM** [comment]
I see, this is disappointing, but apple isn't known for its software infrastructure in any way, so it isn't surprising as well...

**Comment by louwers** [comment]
@HarelM Any chance you could create a **repo-stats** repo for me?

I want a separate repo because I have to give this action push access.

**Comment by HarelM** [comment]
What exactly do you need? for me to create a repo called "repo-stats" and give you admin rights?

**Comment by louwers** [comment]
That would be great!

**Comment by HarelM** [comment]
public, right?

**Comment by louwers** [comment]
Yes, thanks!

**Comment by HarelM** [comment]
Done.
https://github.com/maplibre/repo-stats
