### ISSUE TITLE
Onboarding repository maplibre-gl-inspect

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre#359]
https://github.com/maplibre/maplibre-gl-inspect OR `maplibre-inspect` (?)

## Motivation
**The original [mapbox-gl-inspect](https://github.com/lukasmartinelli/mapbox-gl-inspect) is unmaintained, and is a good web plugin for Maputnik**

## Acceptance
- [x] Any two board members must agree to accept a new repository.
  **Approved by:** @nyurik @HarelM 

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://slack.openstreetmap.us), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/SECURITY_POLICY.txt`
    Add the text:
    ```
    For an up-to-date policy refer to
    https://github.com/maplibre/maplibre/blob/main/SECURITY_POLICY.txt
    ```
- [x] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: @acalcutt 

#### Branches
- [x] The primary branch is named `main`.
- [ ] ~Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*~

## Miscelaneous
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [x] Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by wipfli** [comment]
@acalcutt maintains a fork I think

**Comment by nyurik** [comment]
Oh, thanks @wipfli, I was not aware of https://github.com/acalcutt/maplibre-gl-inspect

@acalcutt would you be interested in moving it to maplibre org, as it is clearly an important and maplibre-focused component that is critical to Maputnik?

**Comment by acalcutt** [comment]
I wouldn't mind moving it under the maplibre org. I originally forked it because I needed it for tileserver-gl, but @wipfli has submitted a few PRs to improve things in shortbread/protomaps so there have been a few updates since then.

**Comment by nyurik** [comment]
If everyone is ok with this (need @HarelM or another board member signoff above) - @acalcutt lets do it, you can just add Harel as an admin to that specific repo, and he will be able to move it, and go through the checklist

**Comment by acalcutt** [comment]
sure, do you want me to wait until the second approval you were requesting?

**Comment by HarelM** [comment]
Approved, I'll see what needs to be done in order to migrate it under maplibre.
@acalcutt does it make sense to change the npm package name to be "more official" from your perspective?

**Comment by HarelM** [comment]
Seems like I didn't get admin permissions so I can't move it, just fork it...

**Comment by HarelM** [comment]
But since there's a fork already, I can try it out on maputnik and open a PR to fix the bug, since it's maintained, so this PR is less "critical"...

**Comment by nyurik** [comment]
@acalcutt Harel needs to be an admin on your repo in order to transfer it

**Comment by acalcutt** [comment]
I've never actually published my version to npm I only used the js files., i think the published as 'maplibre-gl-inspect' is actually @vinayakkulkarni . That was based of my version but converted to typescript https://github.com/geoql/maplibre-gl-inspect.

If you did want to want to publish it I think @maplibre/maplibre-gl-inspect could make sense. It could also make sense to take a look at @vinayakkulkarni's typescript version.

**Comment by HarelM** [comment]
It would make more sense to use the typescript version I believe if @vinayakkulkarni is fine with that.
Although @vinayakkulkarni's version doesn't have the examples that exist in @acalcutt's repo.
So a mix and match would probably be the best direction.
In both cases, it's a handful of files and doing changes there shouldn't be complicated...

**Comment by acalcutt** [comment]
I added @HarelM as a collaborator to the projet, but i'm not sure I see how to make him an admin there.

![image](https://github.com/maplibre/maplibre/assets/3792408/456a6431-2bdd-4b13-8ecb-794f5ecac618)

From what I see at 
![image](https://github.com/maplibre/maplibre/assets/3792408/9bd9e05d-8113-4129-8908-44a80be68d4f)
it seems like it would be there.

**Comment by HarelM** [comment]
It might not be possible for non org related repos, maybe... IDK.

**Comment by nyurik** [comment]
Hmm, maybe you don't actually need to do that for non-org repo - just go to the bottom of the "general" settings page, and click transfer?  The value should be `maplibre/maplibre-gl-inspect` (that's the name we want, right?)

![image](https://github.com/maplibre/maplibre/assets/1641515/1b200d68-d755-4a09-aefd-a0cbc542307d)

**Comment by nyurik** [comment]
oh, I just realized that it is the `org` that's the problem - so just transfer it to harel, and he'll transfer it to maplibre?

**Comment by HarelM** [comment]
The repo has been transferred.
CI is still underway.
@nyurik @wipfli I'm leaving the announcements for your care.

**Comment by HarelM** [comment]
@vinayakkulkarni would still be great to have the typescript code you did in maplibre instead of plain javascript.

**Comment by HarelM** [comment]
I've just completed the typescript migration...
A npm package was published so feel free to annonce:
https://www.npmjs.com/package/@maplibre/maplibre-gl-inspect

**Comment by HarelM** [comment]
@wipfli can you take care of the announcements so we can close this issue?

**Comment by wipfli** [comment]
From the March Newsletter:

> In March 2024, we onboarded [maplibre-gl-inspect](https://github.com/maplibre/maplibre-gl-inspect) into the MapLibre GitHub organization. MapLibre GL Inspect is a small plugin for MapLibre GL JS that allows you to inspect the contents of vector tiles including the attributes of vector tile features. Special thanks to [Andrew Calcutt](https://github.com/acalcutt) who maintained this plugin over the last years and made sure it works with MapLibre GL JS.
