### ISSUE TITLE
MapLibre Voting Members Invitation

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#36]
I am very happy to invite the people in the list below to become MapLibre Voting Members. The Governing Board chose you because we (@lseelenbinder @nyurik @klokan and I) think that you made an important and non-trivial contribution to MapLibre. As a Voting Member, you have the right to participate in the Governing Board election which will take place at the time of FOSS4G, i.e., end of August.

If you accept our invitation and would like to become part of the MapLibre Voting Members, please file a pull request to [VOTING_MEMBERS.md](https://github.com/maplibre/maplibre/blob/main/VOTING_MEMBERS.md) where you add your GitHub handle to the existing list. You find instructions on how to file a pull request [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

If you did not get invited but would like to be a Voting Member, please write it into this issue. We most likely missed some people and I apologize for that in advance...

So, thanks for supporting MapLibre and I am looking forward to your pull requests.

@ambientlight :+1: :envelope: 
@astridx
@atierian :+1: :envelope: 
@bchapuis :+1: :envelope: 
@bdon :+1: :envelope:
@birkskyum :+1: :envelope: 
@boldtrn
@brendan-ward :+1: :envelope: 
@chippieTV :+1: :envelope:
@dayjournal :+1: :envelope: 
@drwestco :+1: :envelope: 
@fredj :+1: :envelope: 
@HarelM :+1: :envelope: 
@hoeflehner :+1: :envelope: 
@JannikGM :+1: :envelope: 
@Joxit :+1: :envelope: 
@jutaz :+1: :envelope: 
@Kanahiro :+1: :envelope: 
@kylebarron
@Malvoz
@marcelnormann
@maxammann :+1: :envelope: 
@METACEO :+1:
@migurski
@mnutt :+1: :envelope: 
@mojodna :+1: :envelope: 
@msbarry :+1: :envelope: 
@muesliq :+1: :envelope: 
@nreese :+1: :envelope: 
@ntadej :+1: :envelope: 
@nvanfleet :+1: :envelope: 
@OlexandrStepanov :+1: :envelope: 
@petr-pokorny-1 :+1:
@petrsloup :+1: :envelope: 
@prozessor13 :+1: :envelope: 
@rbrundritt :+1: :envelope: 
@roblabs :+1: :envelope: 
@rubenmx
@SjoerdPerfors :+1: :envelope: 
@smellyshovel :+1: :envelope: 
@stepankuzmin
@sulewicz :+1: :envelope: 
@thaddmt :+1: :envelope: 
@TomPohys :+1: :envelope: 
@webberig
@xabbu42 :+1: :envelope: 
@ZeLonewolf :+1: :envelope: 
@zstadler :+1: :envelope:

Legend: :+1: means the person accepted the invitation and sent a pull request. :envelope: means the person shared their email address for the voting system.

**Comment by nyurik** [comment]
apparenly github issue only allows 50 names as links, so adding @zstadler and @wipfli himself to ensure they are also in the list

**Comment by wipfli** [comment]
Thanks @nyurik that is a good idea. I dropped the Governing Board members to make space but did not think far enough to ping @zstadler in a new post...

**Comment by dayjournal** [comment]
Hi, @wipfli 
I have created a pull request to add @Kanahiro and @dayjournal.
Thank you! I'm honored to be one of them!

**Comment by JannikGM** [comment]
I think we should add to which organization a member belongs, so the "3 people per organization"-rule becomes more easily enforceable (although it remains hard to enforce as the boundaries and link between organizations is often diffuse).

Regarding me:

I'm employee of [Graphmasters GmbH](https://www.graphmasters.net/), primarily working on map related features / animations and visualizations in our web apps. A couple of colleagues are working on integration of maplibre into our Android and iOS apps (including potential bugfixes or features in the future).

Maplibre has become an integral part of our products and will likely continue to do so.
Topics we are interested in include fluid map animations on the web, car support (such as Android Auto) on mobile and better shield rendering.

**Comment by wipfli** [comment]
Regarding declaring which organization a person works for, I think it would be best to discuss in https://github.com/maplibre/maplibre/discussions/32.

I like the shields in https://zelonewolf.github.io/openstreetmap-americana/#8.76/38.5833/-90.1604 a lot...

**Comment by wipfli** [comment]
We will use a website for the online votes which will require an email address. I will contact the Voting Members directly and ask for their email addresses. As pointed out by @JannikGM and others, it makes sense to publicly declare if a you are paid to work on MapLibre-related stuff. I will ask the Voting Members directly if they would like to declare that they are paid to work on MapLibre...

**Comment by wipfli** [comment]
I think I pinged everyone now in slack or in linkedin except @METACEO. If you did not get a message, please reach out to me directly in slack: https://osmus-slack.herokuapp.com/

**Comment by wipfli** [comment]
I am very glad that 38 people accepted the Voting Membership invitation and have shared their email addresses with me for the voting system. We will now take your email addresses and put them into [opavote.com](https://www.opavote.com/), and send out a test question. 

This will probably mean that you get an email with a link to the test question. Answer this test question such that we can check that everything works fine before we hold the actual election. If you do not receive a test question email until Wednesday, Aug 17th, 2022, please send me a message.

**Comment by wipfli** [comment]
Thankfully we got a nomination to add @Pessimistress as one more Voting Member to the group in #71. So now we don't need to run the bare test question to check that the voting system works. Instead, we will just send out the question:

"Would you like to add @Pessimistress to the MapLibre Voting Members?"

I think we will send out the email for this today. If you should not have gotten something until Thursday, Aug 18th, 2022, please ping me...
