### ISSUE TITLE
Onboarding repository `maplibre/maplibre-gestures-android`

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre#383]
https://github.com/louwers/maplibre-gestures-android

I have updated the dependencies. Demo app runs fine. Tests are passing.

https://github.com/user-attachments/assets/170d6128-6c18-457d-8ade-5f26ffaf3a1a

Added dependency to MapLibre Native Android for the test app (instead of Mapbox SDK).

I will be going over the rest of the items in this list.

I still need to update CI and configure publishing to our Maven Central repo.

## Motivation

[mapbox-gestures-android](https://github.com/mapbox/mapbox-gestures-android) is a dependency of MapLibre Native. It does not appear to be maintained, the dependencies are outdated. I ran into a problem when updating dependencies for MapLibre Native Android, so I decided that it would be a good time to fork it.

## Acceptance
- [ ] Any two board members must agree to accept a new repository.
  **Approved by:** @HarelM <@user2>

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://slack.openstreetmap.us), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/SECURITY_POLICY.txt`
    Add the text:
    ```
    For an up-to-date policy refer to
    https://github.com/maplibre/maplibre/blob/main/SECURITY_POLICY.txt
    ```
- [x] `/CONTRIBUTING.md`
- [ ] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: @louwers

#### Branches
- [x] The primary branch is named `main`.
- [ ] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [x] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] ~Grant admin rights to the board members and automation accounts for packages <list-of-packages>~

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by HarelM** [comment]
This should be a core project, right?

**Comment by louwers** [comment]
@HarelM To build mapbox-gestures-android locally you need access to the Mapbox SDK Registry, so I would need to get a Mapbox account and a Mapbox token. That's not something I want to deal with.

All dependencies are outdated, so I can open a PR and update all of them, but since I can't run releases myself there is not way for me to verify that everything still works.

**Comment by louwers** [comment]
Publishing seems to work https://central.sonatype.com/artifact/org.maplibre.gl/maplibre-android-gestures

**Comment by birkskyum** [comment]
I approve it as well.

**Comment by louwers** [comment]
OK automated releases are now set up, I think this can be closed.

It was announced in the newsletter. We don't need more fanfare, it is just a dependency.
