### ISSUE TITLE
Create Linux ARM GitHub Hosted Runner

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre#413]
For Node.js we need a Linux ARM runner.

There is a one minute video here how to do it: https://youtu.be/cgI6SBP8pEM?si=0MHmgqrunWz-v5tf&t=32

Let's go for the 8-core version. https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates-for-arm64-powered-larger-runners

**Comment by birkskyum** [comment]
ike this? The maplibre-native runner group is scoped to have access only to the single maplibre-native repo - let me know if that’s not ideal.

<img width="870" alt="Screenshot 2024-09-21 at 13 29 31" src="https://github.com/user-attachments/assets/b8ed7955-42dc-478c-90e4-9e45b8df7ca6">
