### ISSUE TITLE
Onboarding repository maplibre/geojson-cpp

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre#417]
https://github.com/maplibre/geojson-cpp

Current repository: https://github.com/louwers/geojson-cpp

## Motivation

[mapbox/geojson-cpp](https://github.com/mapbox/geojson-cpp) is a dependency of MapLibre Native that is no longer maintained.

## Acceptance
- [x] @birkskyum 
- [x] @lseelenbinder 

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) ~and in the readme.~

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, ~name of the OSM-US Slack channel for discussions and an [invite link](https://slack.openstreetmap.us), etc*~
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/SECURITY.md`
- [ ] `/CONTRIBUTING.md`
- [ ] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [ ] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [x] The repo has at least one admin who is ideally not part of the Governing Board: @louwers

#### Branches
- [x] The primary branch is named `main`.
- [x] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [x] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [x] CI automatically runs on all pull requests before merging using GitHub actions

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by louwers** [comment]
I wrote simple CMake build config, added a CI that runs the tests, fixed compilation issues, renamed namespaces and include paths from `mapbox` to `maplibre` and replaced `mapbox/variant.hpp` with `std::variant`.

Once this is transferred I'll update the dependencies of MapLibre Native.

**Comment by birkskyum** [comment]
Thanks! I approve.

**Comment by lseelenbinder** [comment]
Nice! 💯

**Comment by birkskyum** [comment]
It's transferred:
https://github.com/maplibre/geojson-cpp

**Comment by louwers** [comment]
Nice, thanks.

**Comment by birkskyum** [comment]
@louwers , it's resolved now.
