### ISSUE TITLE
Onboarding repository qt-geoservices-maplibre-gl

### ISSUE THREAD

**Issue by ntadej** [maplibre/maplibre#61]
https://github.com/maplibre/qt-geoservices-maplibre-gl

## Motivation

Qt Location is a popular mapping-agnostic library to integrate maps into Qt application. MapBox GL was one of the most feature-complete plugins but is no longer supported due to licensing changes.

While there is an effort to integrate MapLibre into Qt codebase, having the code outside would not bind us to Qt release schedule.

## Acceptance
- [ ] Any two board members must agree to accept a new repository.
  **Approved by:**

## Licensing
- [x] The repo license is BSD-3 or MIT: Only examples are licensed MIT.
- [x] The repo license needs to comply with Qt licensing (LGPL + GPL).
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [ ] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://osmus-slack.herokuapp.com/), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [ ] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [x] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [x] **[Features]** Enable `Preserve this repository`.
- [x] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [x] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [X] The repo has at least one admin who is ideally not part of the Governing Board: @ntadej

#### Branches
- [X] The primary branch is named `main`.
- [x] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [ ] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [x] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [x] CI automatically runs on all pull requests before merging using GitHub actions
- [X] Grant admin rights to the board members and automation accounts for packages: not needed, will use GitHub directly

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [x] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by wipfli** [comment]
I think it would be better to only use an MIT license for this repository. @ntadej can you comment why you chose GPL?

**Comment by ntadej** [comment]
> I think it would be better to only use an MIT license for this repository. @ntadej can you comment why you chose GPL?

I'm not a lawyer but afaik the code can't be just relicensed to a more permissive license. I just kept what was there before. That's also why it's good to have this in a separate repository.

**Comment by wipfli** [comment]
I see thanks for the info. So is the code you took something like a plugin template for Qt?

**Comment by ntadej** [comment]
> I see thanks for the info. So is the code you took something like a plugin template for Qt?

No, it's the old Mapbox code. As it was part of Qt it's licensed like that.

**Comment by wipfli** [comment]
Ah, interesting, now I see that you mention them for example here: https://github.com/maplibre/qt-geoservices-maplibre-gl/blob/main/src/qgeomapmaplibregl.h

Maybe you can give credits to mapbox also in the readme or so...
