### ISSUE TITLE
Secrets documentation

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#63]
#33 started some documentation of our secrets. I wonder if we should have something like a key manager for MapLibre. The Governing Board members could all have access to that key manager.

In native, the situation is worrying me because we don't have any documentation on how secrets are managed and we will likely not be able to make releases with under the old accounts if something breaks. https://github.com/maplibre/maplibre-gl-native/issues/312

**Comment by wipfli** [comment]
Figma has the MapLibre logo at https://www.figma.com/file/hVmulAVC8dMwYS14ovGd3w/OLD-%2F-MapLibre-Logo-%2F-Visuals

**Comment by birkskyum** [comment]
@wipfli , @klokan , can the Figma credentials be added to Bitwarden? Until we have a good media kit ready, the SVG Export plugin in Figma would be convenient to export single Frames.

**Comment by wipfli** [comment]
I think we do not have a figma account. This was just with the designer's or with maptiler's figma account if I remember correctly...

**Comment by birkskyum** [comment]
We have an account now with the board email it can be transferred to.

**Comment by klokan** [comment]
I guess you just make a copy under the Figma account, right?

Not sure how the transfer would work otherwise.
