### ISSUE TITLE
Voting Member Nominations

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre#71]
Voting Members can nominate other people to become Voting Members as well by posting their GitHub handles in this thread until Thursday, August 11th, 2022. The existing Voting Member will then decide online if they grant the nominated people Voting Membership on Thursday, August 18th, 2022 via an online vote.

**Comment by nyurik** [comment]
@pessimistress

**Comment by wipfli** [comment]
Thanks for the nomination @nyurik. Let's extend the deadline for adding new Voting Members until Monday, Aug 15th, 2022 and then vote on adding the new people on Thursday, Aug 18th, 2022...

**Comment by wipfli** [comment]
We will prepare a vote about adding @Pessimisstress to the MapLibre Voting Members. This vote will also serve as a test run for the Governing Board elections next week such that we can test that all the emails and voting system works...
