### ISSUE TITLE
Wrong borders

### ISSUE THREAD

**Issue by zergius-eggstream** [maplibre/maplibre#8]
![image](https://user-images.githubusercontent.com/5724498/151006579-813e03d6-9d79-4c7e-af80-4378968a7e01.png)
There is a mistake in your map: Crimea is an ukrainian territory, not a russian

**Comment by wipfli** [comment]
Thanks for reporting. The topic of [disputed territories](https://wiki.openstreetmap.org/wiki/Disputed_territories) is indeed not well handled by the current style. Feel free to submit a pull request to https://github.com/maplibre/maplibre.github.io to fix this.

**Comment by wipfli** [comment]
@petr-pokorny-1 what is the process for re-generating the pbfs used in the demotiles repo?

**Comment by wipfli** [comment]
Would be nice if you could join the maplibre slack channel. We had a discussion on this topic 7 months ago. I now linked your issue there.

**Comment by wipfli** [comment]
What would be the easiest way to fix this? Maybe an overlay? Or is there a new version of natural earth?

**Comment by wipfli** [comment]
https://github.com/maplibre/demotiles/pull/9

**Comment by zergius-eggstream** [comment]
Fix screenshot https://user-images.githubusercontent.com/59284/118267966-117aa100-b4bd-11eb-8824-430cbe674191.png at https://github.com/maplibre/demotiles and all will be good ;)
