### ISSUE TITLE
Onboarding repository unassert-rollup-plugin

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre#88]
https://github.com/birkskyum/unassert-rollup-plugin/tree/maplibre-onboarding-files
https://www.npmjs.com/package/unassert-rollup-plugin

## Motivation
maplibre-gl-js already rely on this repository to remove node assert from the source code for release builds - for development builds the assert is not removed but bundled using browserify. It's only used at maplibre, and might as well be under the organisation, both in terms of npm and github. I made a branch that contains the changes needed for this onboarding, but I'd like to know if you think it belongs here of if I should keep it on my personal account.

## Acceptance
- [ ] Any two board members must agree to accept a new repository.
  **Approved by:** <@user1> <@user2>

## Licensing
- [x] The repo license is BSD-3 or MIT.
  *Repos may allow dual-licensing under other open source licenses, e.g. MIT OR Apache.*
- [x] The repo contains `Copyright (c) <year> MapLibre contributors` in license file(s) and in the readme.

## Special files
- [x] `/README.md`
  *Description, link to the main maplibre.org page, name of the OSM-US Slack channel for discussions and an [invite link](https://osmus-slack.herokuapp.com/), etc*
- [x] `/LICENSE`
   *Dual-licensed repos may have additional files like `LICENSE-MIT` and `LICENSE-APACHE`*
- [x] `/CONTRIBUTING.md`
- [x] The repo has Pull Request and Issue Templates in `/.github` dir.
- [x] The repo has `/.github/FUNDING.yml` file copied from [maplibre-gl-js/funding](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/FUNDING.yml)
- [x] `/CODE_OF_CONDUCT.md`
  *This file should only link to our [primary code of conduct](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md). Use this markup for consistency:*
 `# Contributor Covenant`
 `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)](https://github.com/maplibre/maplibre/blob/main/CODE_OF_CONDUCT.md)`

#### General page
- [X] **[Features]** Disable unused features like wiki.
- [x] **[Features]** Enable `Sponsorships` checkbox (see also FUNDING.yaml above).
- [X] **[Features]** Enable `Preserve this repository`.
- [X] **[Pull Requests]** Community is encouraged to use `squash merge`. Disable other merge types if possible.
- [X] **[Pull Requests]** Enable `Automatically delete head branches`.

#### Access
- [X] The repo has at least one admin who is ideally not part of the Governing Board: <@user>

#### Branches
- [X] The primary branch is named `main`.
- [X] Set up branch rules to require CI pass and an approval before merge.
  *For smaller projects it might be OK to ignore this rule.*

## Miscelaneous
- [X] The repo must not have any personal branches.
  *All work should be done on forks and submitted via PRs, including by the admins.*
- [X] Repo has a proper GitHub description and an optional web site
  *Use the gear icon in the upper right corner of the repo page.*
- [X] CI automatically runs on all pull requests before merging using GitHub actions
- [ ] Grant admin rights to the board members and automation accounts for packages <list-of-packages>
  - [npmjs.com](https://www.npmjs.com/): package settings / invite:  `maplibreorg nyurik klokan lseelenbinder wipfli`
  - [crates.io](https://crates.io/): package settings / add owner: `nyurik klokan lseelenbinder wipfli`

## Community
- [ ] The new repo has been announced in the `#maplibre` OSMUS slack channel.
- [ ] The new repo has been announced in the next monthly meeting of the Technical Steering Committee.
- [ ] The new repo has been announced in the `@maplibre` twitter.

**Comment by birkskyum** [comment]
It's not completely ready in terms of mentions of MapLibre etc., but I opened an issue to start the onboarding process and get feedback on it.

**Comment by wipfli** [comment]
Thanks for opening this issue, @birkskyum. I think that MapLibre's scope does not include a tool as generic as this one. Let me know if I am missing something... To me this seems to not tied to mapping software, right?

**Comment by HarelM** [comment]
Can't we simply remove all the asserts and reduce this dependency?

**Comment by birkskyum** [comment]
It is generic, and we can keep a status quo for sure, it was just important for me to emphasize that a handover is possible from my side if there's a wish for that at some point, so I don't sit on something that is technically shared property.

**Comment by wipfli** [comment]
Thanks for the clarification!

**Comment by birkskyum** [comment]
> Can't we simply remove all the asserts and reduce this dependency?

we can, i did make a branch for that, but i was hesitant to just remove all the assets because it seemed like there might be some information in the them that could be convert to unit or integration tests.

**Comment by HarelM** [comment]
Your branch feels to me like an effort in the right direction.
You could, in theory, add some console logging and see if the asserts are called in the tests maybe to better understand the coverage.
But, overall, they don't help in production as they are not there and I'm not sure who uses the debug version assuming it is not removed there as well...
Overall, dead code IMHO.

**Comment by birkskyum** [comment]
Alright, then let's move towards that instead. It's true that they don't provide value for the production build, but none of our tests does, and it seems like our integration and unit tests include these asserts, as well as the start-debug server, so in all those cases an unmet assertion would let us know something is off. But I don't know if they actually increase our coverage.

**Comment by birkskyum** [comment]
Closing, because we've finally managed to refactor unassert-rollup-plugin out of maplibre-gl-js ( see https://github.com/maplibre/maplibre-gl-js/pull/1485 )
